# Generated by Django 5.0.3 on 2026-04-29 03:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_description', models.TextField()),
                ('impact_time_hours', models.FloatField(help_text='Time lost per week in hours')),
                ('impact_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('suggested_solution', models.TextField()),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=10)),
                ('estimated_time_saved_hours', models.FloatField()),
                ('implementation_steps', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insights', to='businesses.submission')),
            ],
        ),
    ]
